### ISSUE TITLE
App does not run

### ISSUE THREAD

**Issue by saurabhabh** [karissa/chatmesh-desktop#9]
I am trying to run the project but getting below error. I have made no changes to the project. 

node version - 10.13.0
npm version  - 6.4.1

I am running on a windows 10 machine. 

![image](https://user-images.githubusercontent.com/8706481/50433866-d170ee80-0900-11e9-8b02-d1b935c96bbd.png)

**Comment by okdistribute** [comment]
hi this has now been deprecated/moved to http://github.com/cabal-club/cabal-desktop/
